controllers:
    resource:
        path: ../src/Infrastructure/Symfony/Controller/
        namespace: App\Infrastructure\Symfony\Controller
    type: attribute

signin:
  path: /api/auth/signin
  methods: ['POST']