api_platform:
    title: LAH Application
    description: API Student Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        format: json

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        persist_authorization: true

    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']

    resource_class_directories:
        # - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/Infrastructure/Symfony/Entity'
        # - '%kernel.project_dir%/src/Api'
        - '%kernel.project_dir%/src/Infrastructure/ApiPlatform'

    show_webby: false