doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        # 'DoctrineMigrations': '%kernel.project_dir%/migrations'
        # 'App\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Migrations'
        'DoctrineMigrations': '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Migrations'
    enable_profiler: false
